# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       mytraceroute

# >> macros
# << macros
%define upstream_name mtr

Summary:    my traceroute, an advanced traceroute utility
Version:    0.95
Release:    2
Group:      Applications/Internet
License:    GPLv2
URL:        https://github.com/traviscross/mtr
Source0:    %{name}-%{version}.tar.gz
Source100:  mytraceroute.yaml
Requires(post): libcap
BuildRequires:  pkgconfig(ncursesw)
BuildRequires:  autoconf
BuildRequires:  automake
Provides:   openrepos-mtr = %{version}
Provides:   %{upstream_name} = %{version}
Conflicts:   openrepos-mtr
Obsoletes:   openrepos-mtr < %{version}

%description
mtr combines the functionality of the 'traceroute' and 'ping' programs in a
single network diagnostic tool.

As mtr starts, it investigates the network connection between the host mtr runs
on and a user-specified destination host. After it determines the address of
each network hop between the machines, it sends a sequence of ICMP ECHO
requests to each one to determine the quality of the link to each machine. As
it does this, it prints running statistics about each machine.

%if "%{?vendor}" == "chum"
PackageName: MyTraceRoute (mtr)
Type: console-application
PackagerName: nephros
Categories:
 - Network
 - Utility
Custom:
  Repo: https://github.com/traviscross/mtr
  PackagingRepo: https://github.com/sailfishos-chum/mtr
Icon: https://github.com/sailfishos-chum/mtr/raw/master/mtr_icon_sailfish.png
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
aclocal $ACLOCAL_OPTS
autoheader
automake --add-missing --copy --foreign
autoconf --force

# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    -q -C \
    --without-gtk \
    --enable-ipv6


# >> build post
#make %%{?_smp_mflags}
%make_build
# << build post

%install
rm -rf %{buildroot}
# >> install pre
make install-sbinPROGRAMS DESTDIR="%{buildroot}"
#%%make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%defattr(-, root, root, 0755)
%license COPYING
%{_sbindir}/*
# >> files
# << files
